#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/sdo/ce/examples/extensions/scale
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/include/utils.tci:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/include/utils.tci
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs
/home/houstar/ezsdk/component-sources/codec_engine_3_22_01_06/codec_engine.bld:
package.mak: /home/houstar/ezsdk/component-sources/codec_engine_3_22_01_06/codec_engine.bld
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs
package.mak: package.bld
endif

ti.targets.C674.rootDir ?= /home/houstar/ezsdk/dsp-devkit/cgt6x_7_3_4
ti.targets.packageBase ?= /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/
ti.targets.elf.C674.rootDir ?= /home/houstar/ezsdk/dsp-devkit/cgt6x_7_3_4
ti.targets.elf.packageBase ?= /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/
.PRECIOUS: $(XDCCFGDIR)/%.o674
.PHONY: all,674 .dlls,674 .executables,674 test,674
all,674: .executables,674
.executables,674: .libraries,674
.executables,674: .dlls,674
.dlls,674: .libraries,674
.libraries,674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,674
	@$(ECHO) xdc .executables,674
	@$(ECHO) xdc .libraries,674
	@$(ECHO) xdc .dlls,674

.PRECIOUS: $(XDCCFGDIR)/%.oe674
.PHONY: all,e674 .dlls,e674 .executables,e674 test,e674
all,e674: .executables,e674
.executables,e674: .libraries,e674
.executables,e674: .dlls,e674
.dlls,e674: .libraries,e674
.libraries,e674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e674
	@$(ECHO) xdc .executables,e674
	@$(ECHO) xdc .libraries,e674
	@$(ECHO) xdc .dlls,e674


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.sdo.ce.examples.extensions.scale.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.sdo.ce.examples.extensions.scale" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.sdo.ce.examples.extensions.scale $@

.libraries,674 .libraries: lib/scale.a674

-include lib/scale.a674.mak
lib/scale.a674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.o674 package/lib/lib/scale/scale.o674 package/lib/lib/scale/scale_skel.o674 package/lib/lib/scale/scale_stubs.o674  into $@ ...
	$(ti.targets.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.o674 package/lib/lib/scale/scale.o674 package/lib/lib/scale/scale_skel.o674 package/lib/lib/scale/scale_stubs.o674 
lib/scale.a674: export C_DIR=
lib/scale.a674: PATH:=$(ti.targets.C674.rootDir)/bin/:$(PATH)

clean,674 clean::
	-$(RM) lib/scale.a674
.libraries,674 .libraries: lib/scale_debug.a674

-include lib/scale_debug.a674.mak
lib/scale_debug.a674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.o674 package/lib/lib/scale_debug/scale.o674 package/lib/lib/scale_debug/scale_skel.o674 package/lib/lib/scale_debug/scale_stubs.o674  into $@ ...
	$(ti.targets.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.o674 package/lib/lib/scale_debug/scale.o674 package/lib/lib/scale_debug/scale_skel.o674 package/lib/lib/scale_debug/scale_stubs.o674 
lib/scale_debug.a674: export C_DIR=
lib/scale_debug.a674: PATH:=$(ti.targets.C674.rootDir)/bin/:$(PATH)

clean,674 clean::
	-$(RM) lib/scale_debug.a674
.libraries,e674 .libraries: lib/scale.ae674

-include lib/scale.ae674.mak
lib/scale.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.oe674 package/lib/lib/scale/scale.oe674 package/lib/lib/scale/scale_skel.oe674 package/lib/lib/scale/scale_stubs.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.oe674 package/lib/lib/scale/scale.oe674 package/lib/lib/scale/scale_skel.oe674 package/lib/lib/scale/scale_stubs.oe674 
lib/scale.ae674: export C_DIR=
lib/scale.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/scale.ae674
.libraries,e674 .libraries: lib/scale_debug.ae674

-include lib/scale_debug.ae674.mak
lib/scale_debug.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.oe674 package/lib/lib/scale_debug/scale.oe674 package/lib/lib/scale_debug/scale_skel.oe674 package/lib/lib/scale_debug/scale_stubs.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.oe674 package/lib/lib/scale_debug/scale.oe674 package/lib/lib/scale_debug/scale_skel.oe674 package/lib/lib/scale_debug/scale_stubs.oe674 
lib/scale_debug.ae674: export C_DIR=
lib/scale_debug.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/scale_debug.ae674
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.sdo.ce.examples.extensions.scale.o674,copy
package_ti.sdo.ce.examples.extensions.scale.o674,copy : package_ti.sdo.ce.examples.extensions.scale.o674,0,copy package_ti.sdo.ce.examples.extensions.scale.o674,1,copy 
	@

package_ti.sdo.ce.examples.extensions.scale.o674,0,copy : package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.o674
package_ti.sdo.ce.examples.extensions.scale.o674,1,copy : package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.o674
.PHONY: package_ti.sdo.ce.examples.extensions.scale.s674,copy
package_ti.sdo.ce.examples.extensions.scale.s674,copy : package_ti.sdo.ce.examples.extensions.scale.s674,0,copy package_ti.sdo.ce.examples.extensions.scale.s674,1,copy 
	@

package_ti.sdo.ce.examples.extensions.scale.s674,0,copy : package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.s674
package_ti.sdo.ce.examples.extensions.scale.s674,1,copy : package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.s674
.PHONY: scale.o674,copy
scale.o674,copy : scale.o674,0,copy scale.o674,1,copy 
	@

scale.o674,0,copy : package/lib/lib/scale/scale.o674
scale.o674,1,copy : package/lib/lib/scale_debug/scale.o674
.PHONY: scale.s674,copy
scale.s674,copy : scale.s674,0,copy scale.s674,1,copy 
	@

scale.s674,0,copy : package/lib/lib/scale/scale.s674
scale.s674,1,copy : package/lib/lib/scale_debug/scale.s674
.PHONY: scale_skel.o674,copy
scale_skel.o674,copy : scale_skel.o674,0,copy scale_skel.o674,1,copy 
	@

scale_skel.o674,0,copy : package/lib/lib/scale/scale_skel.o674
scale_skel.o674,1,copy : package/lib/lib/scale_debug/scale_skel.o674
.PHONY: scale_skel.s674,copy
scale_skel.s674,copy : scale_skel.s674,0,copy scale_skel.s674,1,copy 
	@

scale_skel.s674,0,copy : package/lib/lib/scale/scale_skel.s674
scale_skel.s674,1,copy : package/lib/lib/scale_debug/scale_skel.s674
.PHONY: scale_stubs.o674,copy
scale_stubs.o674,copy : scale_stubs.o674,0,copy scale_stubs.o674,1,copy 
	@

scale_stubs.o674,0,copy : package/lib/lib/scale/scale_stubs.o674
scale_stubs.o674,1,copy : package/lib/lib/scale_debug/scale_stubs.o674
.PHONY: scale_stubs.s674,copy
scale_stubs.s674,copy : scale_stubs.s674,0,copy scale_stubs.s674,1,copy 
	@

scale_stubs.s674,0,copy : package/lib/lib/scale/scale_stubs.s674
scale_stubs.s674,1,copy : package/lib/lib/scale_debug/scale_stubs.s674
.PHONY: package_ti.sdo.ce.examples.extensions.scale.oe674,copy
package_ti.sdo.ce.examples.extensions.scale.oe674,copy : package_ti.sdo.ce.examples.extensions.scale.oe674,0,copy package_ti.sdo.ce.examples.extensions.scale.oe674,1,copy 
	@

package_ti.sdo.ce.examples.extensions.scale.oe674,0,copy : package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.oe674
package_ti.sdo.ce.examples.extensions.scale.oe674,1,copy : package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.oe674
.PHONY: package_ti.sdo.ce.examples.extensions.scale.se674,copy
package_ti.sdo.ce.examples.extensions.scale.se674,copy : package_ti.sdo.ce.examples.extensions.scale.se674,0,copy package_ti.sdo.ce.examples.extensions.scale.se674,1,copy 
	@

package_ti.sdo.ce.examples.extensions.scale.se674,0,copy : package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.se674
package_ti.sdo.ce.examples.extensions.scale.se674,1,copy : package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.se674
.PHONY: scale.oe674,copy
scale.oe674,copy : scale.oe674,0,copy scale.oe674,1,copy 
	@

scale.oe674,0,copy : package/lib/lib/scale/scale.oe674
scale.oe674,1,copy : package/lib/lib/scale_debug/scale.oe674
.PHONY: scale.se674,copy
scale.se674,copy : scale.se674,0,copy scale.se674,1,copy 
	@

scale.se674,0,copy : package/lib/lib/scale/scale.se674
scale.se674,1,copy : package/lib/lib/scale_debug/scale.se674
.PHONY: scale_skel.oe674,copy
scale_skel.oe674,copy : scale_skel.oe674,0,copy scale_skel.oe674,1,copy 
	@

scale_skel.oe674,0,copy : package/lib/lib/scale/scale_skel.oe674
scale_skel.oe674,1,copy : package/lib/lib/scale_debug/scale_skel.oe674
.PHONY: scale_skel.se674,copy
scale_skel.se674,copy : scale_skel.se674,0,copy scale_skel.se674,1,copy 
	@

scale_skel.se674,0,copy : package/lib/lib/scale/scale_skel.se674
scale_skel.se674,1,copy : package/lib/lib/scale_debug/scale_skel.se674
.PHONY: scale_stubs.oe674,copy
scale_stubs.oe674,copy : scale_stubs.oe674,0,copy scale_stubs.oe674,1,copy 
	@

scale_stubs.oe674,0,copy : package/lib/lib/scale/scale_stubs.oe674
scale_stubs.oe674,1,copy : package/lib/lib/scale_debug/scale_stubs.oe674
.PHONY: scale_stubs.se674,copy
scale_stubs.se674,copy : scale_stubs.se674,0,copy scale_stubs.se674,1,copy 
	@

scale_stubs.se674,0,copy : package/lib/lib/scale/scale_stubs.se674
scale_stubs.se674,1,copy : package/lib/lib/scale_debug/scale_stubs.se674

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_sdo_ce_examples_extensions_scale
ti_sdo_ce_examples_extensions_scale.tar: package/package.bld.xml
ti_sdo_ce_examples_extensions_scale.tar: package/package.ext.xml
ti_sdo_ce_examples_extensions_scale.tar: package/package.rel.dot
ti_sdo_ce_examples_extensions_scale.tar: package/build.cfg
ti_sdo_ce_examples_extensions_scale.tar: package/package.xdc.inc
ti_sdo_ce_examples_extensions_scale.tar: scale.h
ti_sdo_ce_examples_extensions_scale.tar: package/package.cfg.xdc.inc
ti_sdo_ce_examples_extensions_scale.tar: lib/scale.a674
ti_sdo_ce_examples_extensions_scale.tar: lib/scale_debug.a674
ti_sdo_ce_examples_extensions_scale.tar: lib/scale.ae674
ti_sdo_ce_examples_extensions_scale.tar: lib/scale_debug.ae674
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_sdo_ce_examples_extensions_scale.tar.dep
endif
package/rel/ti_sdo_ce_examples_extensions_scale/ti/sdo/ce/examples/extensions/scale/package/package.rel.xml:

ti_sdo_ce_examples_extensions_scale.tar: package/rel/ti_sdo_ce_examples_extensions_scale.xdc.inc package/rel/ti_sdo_ce_examples_extensions_scale/ti/sdo/ce/examples/extensions/scale/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_sdo_ce_examples_extensions_scale.xdc.inc,package/rel/ti_sdo_ce_examples_extensions_scale.tar.dep)


release release,ti_sdo_ce_examples_extensions_scale: all ti_sdo_ce_examples_extensions_scale.tar
clean:: .clean
	-$(RM) ti_sdo_ce_examples_extensions_scale.tar
	-$(RM) package/rel/ti_sdo_ce_examples_extensions_scale.xdc.inc
	-$(RM) package/rel/ti_sdo_ce_examples_extensions_scale.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/scale))
    $(shell $(MKDIR) package/lib/lib/scale)
endif
ifeq (,$(wildcard package/lib/lib/scale/package))
    $(shell $(MKDIR) package/lib/lib/scale/package)
endif
ifeq (,$(wildcard package/lib/lib/scale_debug))
    $(shell $(MKDIR) package/lib/lib/scale_debug)
endif
ifeq (,$(wildcard package/lib/lib/scale_debug/package))
    $(shell $(MKDIR) package/lib/lib/scale_debug/package)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.sdo.ce.examples.extensions.scale.pjt
