#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/sdo/ce/examples/codecs/faacenc
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/include/utils.tci:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/include/utils.tci
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs
/home/houstar/ezsdk/component-sources/codec_engine_3_22_01_06/codec_engine.bld:
package.mak: /home/houstar/ezsdk/component-sources/codec_engine_3_22_01_06/codec_engine.bld
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs
/home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs:
package.mak: /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs
package.mak: package.bld
endif

ti.targets.C674.rootDir ?= /home/houstar/ezsdk/dsp-devkit/cgt6x_7_3_4
ti.targets.packageBase ?= /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/
ti.targets.elf.C674.rootDir ?= /home/houstar/ezsdk/dsp-devkit/cgt6x_7_3_4
ti.targets.elf.packageBase ?= /home/houstar/ezsdk/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/
.PRECIOUS: $(XDCCFGDIR)/%.o674
.PHONY: all,674 .dlls,674 .executables,674 test,674
all,674: .executables,674
.executables,674: .libraries,674
.executables,674: .dlls,674
.dlls,674: .libraries,674
.libraries,674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,674
	@$(ECHO) xdc .executables,674
	@$(ECHO) xdc .libraries,674
	@$(ECHO) xdc .dlls,674

.PRECIOUS: $(XDCCFGDIR)/%.oe674
.PHONY: all,e674 .dlls,e674 .executables,e674 test,e674
all,e674: .executables,e674
.executables,e674: .libraries,e674
.executables,e674: .dlls,e674
.dlls,e674: .libraries,e674
.libraries,e674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e674
	@$(ECHO) xdc .executables,e674
	@$(ECHO) xdc .libraries,e674
	@$(ECHO) xdc .dlls,e674


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.sdo.ce.examples.codecs.faacenc.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.sdo.ce.examples.codecs.faacenc" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.sdo.ce.examples.codecs.faacenc $@

.libraries,674 .libraries: lib/faacenc.a674

-include lib/faacenc.a674.mak
lib/faacenc.a674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/faacenc/package/package_ti.sdo.ce.examples.codecs.faacenc.o674 package/lib/lib/faacenc/faacenc_copy.o674 package/lib/lib/faacenc/aacquant.o674 package/lib/lib/faacenc/bitstream.o674 package/lib/lib/faacenc/faacenc.o674 package/lib/lib/faacenc/filtbank.o674 package/lib/lib/faacenc/huffman.o674 package/lib/lib/faacenc/midside.o674 package/lib/lib/faacenc/tns.o674 package/lib/lib/faacenc/backpred.o674 package/lib/lib/faacenc/channels.o674 package/lib/lib/faacenc/fft.o674 package/lib/lib/faacenc/frame.o674 package/lib/lib/faacenc/ltp.o674 package/lib/lib/faacenc/psychkni.o674 package/lib/lib/faacenc/util.o674 package/lib/lib/faacenc/kiss_fft/kiss_fft.o674 package/lib/lib/faacenc/kiss_fft/kiss_fftr.o674  into $@ ...
	$(ti.targets.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/faacenc/package/package_ti.sdo.ce.examples.codecs.faacenc.o674 package/lib/lib/faacenc/faacenc_copy.o674 package/lib/lib/faacenc/aacquant.o674 package/lib/lib/faacenc/bitstream.o674 package/lib/lib/faacenc/faacenc.o674 package/lib/lib/faacenc/filtbank.o674 package/lib/lib/faacenc/huffman.o674 package/lib/lib/faacenc/midside.o674 package/lib/lib/faacenc/tns.o674 package/lib/lib/faacenc/backpred.o674 package/lib/lib/faacenc/channels.o674 package/lib/lib/faacenc/fft.o674 package/lib/lib/faacenc/frame.o674 package/lib/lib/faacenc/ltp.o674 package/lib/lib/faacenc/psychkni.o674 package/lib/lib/faacenc/util.o674 package/lib/lib/faacenc/kiss_fft/kiss_fft.o674 package/lib/lib/faacenc/kiss_fft/kiss_fftr.o674 
lib/faacenc.a674: export C_DIR=
lib/faacenc.a674: PATH:=$(ti.targets.C674.rootDir)/bin/:$(PATH)

clean,674 clean::
	-$(RM) lib/faacenc.a674
.libraries,e674 .libraries: lib/faacenc.ae674

-include lib/faacenc.ae674.mak
lib/faacenc.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/faacenc/package/package_ti.sdo.ce.examples.codecs.faacenc.oe674 package/lib/lib/faacenc/faacenc_copy.oe674 package/lib/lib/faacenc/aacquant.oe674 package/lib/lib/faacenc/bitstream.oe674 package/lib/lib/faacenc/faacenc.oe674 package/lib/lib/faacenc/filtbank.oe674 package/lib/lib/faacenc/huffman.oe674 package/lib/lib/faacenc/midside.oe674 package/lib/lib/faacenc/tns.oe674 package/lib/lib/faacenc/backpred.oe674 package/lib/lib/faacenc/channels.oe674 package/lib/lib/faacenc/fft.oe674 package/lib/lib/faacenc/frame.oe674 package/lib/lib/faacenc/ltp.oe674 package/lib/lib/faacenc/psychkni.oe674 package/lib/lib/faacenc/util.oe674 package/lib/lib/faacenc/kiss_fft/kiss_fft.oe674 package/lib/lib/faacenc/kiss_fft/kiss_fftr.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/faacenc/package/package_ti.sdo.ce.examples.codecs.faacenc.oe674 package/lib/lib/faacenc/faacenc_copy.oe674 package/lib/lib/faacenc/aacquant.oe674 package/lib/lib/faacenc/bitstream.oe674 package/lib/lib/faacenc/faacenc.oe674 package/lib/lib/faacenc/filtbank.oe674 package/lib/lib/faacenc/huffman.oe674 package/lib/lib/faacenc/midside.oe674 package/lib/lib/faacenc/tns.oe674 package/lib/lib/faacenc/backpred.oe674 package/lib/lib/faacenc/channels.oe674 package/lib/lib/faacenc/fft.oe674 package/lib/lib/faacenc/frame.oe674 package/lib/lib/faacenc/ltp.oe674 package/lib/lib/faacenc/psychkni.oe674 package/lib/lib/faacenc/util.oe674 package/lib/lib/faacenc/kiss_fft/kiss_fft.oe674 package/lib/lib/faacenc/kiss_fft/kiss_fftr.oe674 
lib/faacenc.ae674: export C_DIR=
lib/faacenc.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/faacenc.ae674
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
package_ti.sdo.ce.examples.codecs.faacenc.o674,copy : package/lib/lib/faacenc/package/package_ti.sdo.ce.examples.codecs.faacenc.o674
package_ti.sdo.ce.examples.codecs.faacenc.s674,copy : package/lib/lib/faacenc/package/package_ti.sdo.ce.examples.codecs.faacenc.s674
faacenc_copy.o674,copy : package/lib/lib/faacenc/faacenc_copy.o674
faacenc_copy.s674,copy : package/lib/lib/faacenc/faacenc_copy.s674
aacquant.o674,copy : package/lib/lib/faacenc/aacquant.o674
aacquant.s674,copy : package/lib/lib/faacenc/aacquant.s674
bitstream.o674,copy : package/lib/lib/faacenc/bitstream.o674
bitstream.s674,copy : package/lib/lib/faacenc/bitstream.s674
faacenc.o674,copy : package/lib/lib/faacenc/faacenc.o674
faacenc.s674,copy : package/lib/lib/faacenc/faacenc.s674
filtbank.o674,copy : package/lib/lib/faacenc/filtbank.o674
filtbank.s674,copy : package/lib/lib/faacenc/filtbank.s674
huffman.o674,copy : package/lib/lib/faacenc/huffman.o674
huffman.s674,copy : package/lib/lib/faacenc/huffman.s674
midside.o674,copy : package/lib/lib/faacenc/midside.o674
midside.s674,copy : package/lib/lib/faacenc/midside.s674
tns.o674,copy : package/lib/lib/faacenc/tns.o674
tns.s674,copy : package/lib/lib/faacenc/tns.s674
backpred.o674,copy : package/lib/lib/faacenc/backpred.o674
backpred.s674,copy : package/lib/lib/faacenc/backpred.s674
channels.o674,copy : package/lib/lib/faacenc/channels.o674
channels.s674,copy : package/lib/lib/faacenc/channels.s674
fft.o674,copy : package/lib/lib/faacenc/fft.o674
fft.s674,copy : package/lib/lib/faacenc/fft.s674
frame.o674,copy : package/lib/lib/faacenc/frame.o674
frame.s674,copy : package/lib/lib/faacenc/frame.s674
ltp.o674,copy : package/lib/lib/faacenc/ltp.o674
ltp.s674,copy : package/lib/lib/faacenc/ltp.s674
psychkni.o674,copy : package/lib/lib/faacenc/psychkni.o674
psychkni.s674,copy : package/lib/lib/faacenc/psychkni.s674
util.o674,copy : package/lib/lib/faacenc/util.o674
util.s674,copy : package/lib/lib/faacenc/util.s674
kiss_fft.o674,copy : package/lib/lib/faacenc/kiss_fft/kiss_fft.o674
kiss_fft.s674,copy : package/lib/lib/faacenc/kiss_fft/kiss_fft.s674
kiss_fftr.o674,copy : package/lib/lib/faacenc/kiss_fft/kiss_fftr.o674
kiss_fftr.s674,copy : package/lib/lib/faacenc/kiss_fft/kiss_fftr.s674
package_ti.sdo.ce.examples.codecs.faacenc.oe674,copy : package/lib/lib/faacenc/package/package_ti.sdo.ce.examples.codecs.faacenc.oe674
package_ti.sdo.ce.examples.codecs.faacenc.se674,copy : package/lib/lib/faacenc/package/package_ti.sdo.ce.examples.codecs.faacenc.se674
faacenc_copy.oe674,copy : package/lib/lib/faacenc/faacenc_copy.oe674
faacenc_copy.se674,copy : package/lib/lib/faacenc/faacenc_copy.se674
aacquant.oe674,copy : package/lib/lib/faacenc/aacquant.oe674
aacquant.se674,copy : package/lib/lib/faacenc/aacquant.se674
bitstream.oe674,copy : package/lib/lib/faacenc/bitstream.oe674
bitstream.se674,copy : package/lib/lib/faacenc/bitstream.se674
faacenc.oe674,copy : package/lib/lib/faacenc/faacenc.oe674
faacenc.se674,copy : package/lib/lib/faacenc/faacenc.se674
filtbank.oe674,copy : package/lib/lib/faacenc/filtbank.oe674
filtbank.se674,copy : package/lib/lib/faacenc/filtbank.se674
huffman.oe674,copy : package/lib/lib/faacenc/huffman.oe674
huffman.se674,copy : package/lib/lib/faacenc/huffman.se674
midside.oe674,copy : package/lib/lib/faacenc/midside.oe674
midside.se674,copy : package/lib/lib/faacenc/midside.se674
tns.oe674,copy : package/lib/lib/faacenc/tns.oe674
tns.se674,copy : package/lib/lib/faacenc/tns.se674
backpred.oe674,copy : package/lib/lib/faacenc/backpred.oe674
backpred.se674,copy : package/lib/lib/faacenc/backpred.se674
channels.oe674,copy : package/lib/lib/faacenc/channels.oe674
channels.se674,copy : package/lib/lib/faacenc/channels.se674
fft.oe674,copy : package/lib/lib/faacenc/fft.oe674
fft.se674,copy : package/lib/lib/faacenc/fft.se674
frame.oe674,copy : package/lib/lib/faacenc/frame.oe674
frame.se674,copy : package/lib/lib/faacenc/frame.se674
ltp.oe674,copy : package/lib/lib/faacenc/ltp.oe674
ltp.se674,copy : package/lib/lib/faacenc/ltp.se674
psychkni.oe674,copy : package/lib/lib/faacenc/psychkni.oe674
psychkni.se674,copy : package/lib/lib/faacenc/psychkni.se674
util.oe674,copy : package/lib/lib/faacenc/util.oe674
util.se674,copy : package/lib/lib/faacenc/util.se674
kiss_fft.oe674,copy : package/lib/lib/faacenc/kiss_fft/kiss_fft.oe674
kiss_fft.se674,copy : package/lib/lib/faacenc/kiss_fft/kiss_fft.se674
kiss_fftr.oe674,copy : package/lib/lib/faacenc/kiss_fft/kiss_fftr.oe674
kiss_fftr.se674,copy : package/lib/lib/faacenc/kiss_fft/kiss_fftr.se674

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_sdo_ce_examples_codecs_faacenc
ti_sdo_ce_examples_codecs_faacenc.tar: package/package.bld.xml
ti_sdo_ce_examples_codecs_faacenc.tar: package/package.ext.xml
ti_sdo_ce_examples_codecs_faacenc.tar: package/package.rel.dot
ti_sdo_ce_examples_codecs_faacenc.tar: package/build.cfg
ti_sdo_ce_examples_codecs_faacenc.tar: package/package.xdc.inc
ti_sdo_ce_examples_codecs_faacenc.tar: package/package.cfg.xdc.inc
ti_sdo_ce_examples_codecs_faacenc.tar: lib/faacenc.a674
ti_sdo_ce_examples_codecs_faacenc.tar: lib/faacenc.ae674
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_sdo_ce_examples_codecs_faacenc.tar.dep
endif
package/rel/ti_sdo_ce_examples_codecs_faacenc/ti/sdo/ce/examples/codecs/faacenc/package/package.rel.xml:

ti_sdo_ce_examples_codecs_faacenc.tar: package/rel/ti_sdo_ce_examples_codecs_faacenc.xdc.inc package/rel/ti_sdo_ce_examples_codecs_faacenc/ti/sdo/ce/examples/codecs/faacenc/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_sdo_ce_examples_codecs_faacenc.xdc.inc,package/rel/ti_sdo_ce_examples_codecs_faacenc.tar.dep)


release release,ti_sdo_ce_examples_codecs_faacenc: all ti_sdo_ce_examples_codecs_faacenc.tar
clean:: .clean
	-$(RM) ti_sdo_ce_examples_codecs_faacenc.tar
	-$(RM) package/rel/ti_sdo_ce_examples_codecs_faacenc.xdc.inc
	-$(RM) package/rel/ti_sdo_ce_examples_codecs_faacenc.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/faacenc))
    $(shell $(MKDIR) package/lib/lib/faacenc)
endif
ifeq (,$(wildcard package/lib/lib/faacenc/package))
    $(shell $(MKDIR) package/lib/lib/faacenc/package)
endif
ifeq (,$(wildcard package/lib/lib/faacenc/kiss_fft))
    $(shell $(MKDIR) package/lib/lib/faacenc/kiss_fft)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.sdo.ce.examples.codecs.faacenc.pjt
